[build]
  publish = "apps/web/out" 
  command = "npm run build:web && npm run build:functions && mkdir -p netlify-functions && cp -r apps/functions/dist/apps/functions/src/* netlify-functions/"

[build.environment]
  NODE_VERSION = "20"

# Function settings
[functions]
  directory = "netlify-functions"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.openai.com; connect-src 'self' https://*.supabase.co https://api.openai.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

# Cache headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  command = "npm run build"
  
[context.production.environment]
  NODE_ENV = "production"

[context.branch-deploy]
  command = "npm run build"

[context.branch-deploy.environment]  
  NODE_ENV = "staging"

[context.dev]
  command = "npm run build"

[context.dev.environment]
  NODE_ENV = "development"